### ISSUE TITLE
CutsceneManager.PlayingInfoのDisposeでOnChangedTimeScaleを追加してしまっている

### ISSUE THREAD

**Issue by gr-yamagami-sho-yamasho** [DaitokuAmy/game-framework#1]
CutsceneManager.PlayingInfoのDisposeでOnChangedTimeScaleを追加してしまっている
https://github.com/DaitokuAmy/game-framework/blob/b5fcdaa17dea7b796a81f9b55e32983380cb7f12/Packages/com.daitokuamy.gameframework/CutsceneSystems/CutsceneManager.cs#L144-L158

**Comment by CA-hironori-ito** [comment]
対応しました！ありがとうございますー！
